apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # This value should be managed securely
  JWT_SECRET: "myJun0913"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app-deployment
  labels:
    app: nest-app
spec:
  replicas: 2 # Increased for high availability
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: youngseon360/june-nest:latest # Updated image name
          imagePullPolicy: IfNotPresent # Assumes local image
          ports:
            - containerPort: 5000 # Corrected port
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            # The following variables are sourced from the postgres-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            # The DATABASE_URL is constructed from the secret values
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"