name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f infra/docker/app.Dockerfile -t june-nest .

      - name: Push to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker tag june-nest june-nest-docker-hub/june-nest:latest
          docker push june-nest-docker-hub/june-nest:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            kubectl apply -f ~/k8s/deployment.yaml
            kubectl apply -f ~/k8s/service.yaml
            kubectl apply -f ~/k8s/db.yaml
