name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -f infra/docker/app.Dockerfile -t june-nest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push image to Docker Hub
        run: |
          docker tag june-nest ${{ secrets.DOCKER_USER }}/june-nest:latest
          docker push ${{ secrets.DOCKER_USER }}/june-nest:latest
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update k8s yaml with image ${GITHUB_SHA} [skip ci]" || echo "No changes to commit"
          git push origin HEAD:master

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with: 
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}          
          script: |
            cd /jun/june-nest
            git pull origin master
            kubectl apply -f ./infra/k8s/
